// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: pkg/server/transport/grpc/proto/payload.proto

package coretransport

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreTransport_Call_FullMethodName   = "/coretransport.CoreTransport/Call"
	CoreTransport_Health_FullMethodName = "/coretransport.CoreTransport/Health"
)

// CoreTransportClient is the client API for CoreTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoreTransport is the gRPC service for inter-service calls within the core framework.
type CoreTransportClient interface {
	// Call forwards a PayloadRequest to the target service and returns its response.
	Call(ctx context.Context, in *PayloadRequest, opts ...grpc.CallOption) (*PayloadResponse, error)
	// Health checks whether the remote service is reachable and healthy.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type coreTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreTransportClient(cc grpc.ClientConnInterface) CoreTransportClient {
	return &coreTransportClient{cc}
}

func (c *coreTransportClient) Call(ctx context.Context, in *PayloadRequest, opts ...grpc.CallOption) (*PayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayloadResponse)
	err := c.cc.Invoke(ctx, CoreTransport_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreTransportClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CoreTransport_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreTransportServer is the server API for CoreTransport service.
// All implementations must embed UnimplementedCoreTransportServer
// for forward compatibility.
//
// CoreTransport is the gRPC service for inter-service calls within the core framework.
type CoreTransportServer interface {
	// Call forwards a PayloadRequest to the target service and returns its response.
	Call(context.Context, *PayloadRequest) (*PayloadResponse, error)
	// Health checks whether the remote service is reachable and healthy.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedCoreTransportServer()
}

// UnimplementedCoreTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreTransportServer struct{}

func (UnimplementedCoreTransportServer) Call(context.Context, *PayloadRequest) (*PayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedCoreTransportServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCoreTransportServer) mustEmbedUnimplementedCoreTransportServer() {}
func (UnimplementedCoreTransportServer) testEmbeddedByValue()                       {}

// UnsafeCoreTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreTransportServer will
// result in compilation errors.
type UnsafeCoreTransportServer interface {
	mustEmbedUnimplementedCoreTransportServer()
}

func RegisterCoreTransportServer(s grpc.ServiceRegistrar, srv CoreTransportServer) {
	// If the following call panics, it indicates UnimplementedCoreTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreTransport_ServiceDesc, srv)
}

func _CoreTransport_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreTransportServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreTransport_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreTransportServer).Call(ctx, req.(*PayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreTransport_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreTransportServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreTransport_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreTransportServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreTransport_ServiceDesc is the grpc.ServiceDesc for CoreTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coretransport.CoreTransport",
	HandlerType: (*CoreTransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _CoreTransport_Call_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _CoreTransport_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/server/transport/grpc/proto/payload.proto",
}
