// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pkg/server/transport/grpc/proto/payload.proto

package coretransport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SourceService string                 `protobuf:"bytes,5,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	TargetService string                 `protobuf:"bytes,9,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	SourcePath    string                 `protobuf:"bytes,10,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	TargetPath    string                 `protobuf:"bytes,11,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	UserId        string                 `protobuf:"bytes,12,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,13,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ClientIp      string                 `protobuf:"bytes,14,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Auth          bool                   `protobuf:"varint,15,opt,name=auth,proto3" json:"auth,omitempty"`
	Data          []byte                 `protobuf:"bytes,16,opt,name=data,proto3" json:"data,omitempty"`
	HttpMethod    string                 `protobuf:"bytes,17,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	Token         string                 `protobuf:"bytes,18,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadRequest) Reset() {
	*x = PayloadRequest{}
	mi := &file_pkg_server_transport_grpc_proto_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadRequest) ProtoMessage() {}

func (x *PayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_transport_grpc_proto_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadRequest.ProtoReflect.Descriptor instead.
func (*PayloadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_server_transport_grpc_proto_payload_proto_rawDescGZIP(), []int{0}
}

func (x *PayloadRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *PayloadRequest) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *PayloadRequest) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *PayloadRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *PayloadRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *PayloadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PayloadRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *PayloadRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *PayloadRequest) GetAuth() bool {
	if x != nil {
		return x.Auth
	}
	return false
}

func (x *PayloadRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PayloadRequest) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *PayloadRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type PayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadResponse) Reset() {
	*x = PayloadResponse{}
	mi := &file_pkg_server_transport_grpc_proto_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadResponse) ProtoMessage() {}

func (x *PayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_transport_grpc_proto_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadResponse.ProtoReflect.Descriptor instead.
func (*PayloadResponse) Descriptor() ([]byte, []int) {
	return file_pkg_server_transport_grpc_proto_payload_proto_rawDescGZIP(), []int{1}
}

func (x *PayloadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PayloadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_server_transport_grpc_proto_payload_proto protoreflect.FileDescriptor

const file_pkg_server_transport_grpc_proto_payload_proto_rawDesc = "" +
	"\n" +
	"-pkg/server/transport/grpc/proto/payload.proto\x12\rcoretransport\"\xf3\x03\n" +
	"\x0ePayloadRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12%\n" +
	"\x0esource_service\x18\x05 \x01(\tR\rsourceService\x12%\n" +
	"\x0etarget_service\x18\t \x01(\tR\rtargetService\x12\x1f\n" +
	"\vsource_path\x18\n" +
	" \x01(\tR\n" +
	"sourcePath\x12\x1f\n" +
	"\vtarget_path\x18\v \x01(\tR\n" +
	"targetPath\x12\x17\n" +
	"\auser_id\x18\f \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\r \x01(\tR\buserName\x12\x1b\n" +
	"\tclient_ip\x18\x0e \x01(\tR\bclientIp\x12\x12\n" +
	"\x04auth\x18\x0f \x01(\bR\x04auth\x12\x12\n" +
	"\x04data\x18\x10 \x01(\fR\x04data\x12\x1f\n" +
	"\vhttp_method\x18\x11 \x01(\tR\n" +
	"httpMethod\x12\x14\n" +
	"\x05token\x18\x12 \x01(\tR\x05tokenJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\b\x10\tR\x0esource_addressR\vsource_portR\x12source_socket_portR\x0etarget_addressR\vtarget_portR\x12target_socket_port\";\n" +
	"\x0fPayloadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2V\n" +
	"\rCoreTransport\x12E\n" +
	"\x04Call\x12\x1d.coretransport.PayloadRequest\x1a\x1e.coretransport.PayloadResponseBLZJgithub.com/digitalwayhk/core/pkg/server/transport/grpc/proto;coretransportb\x06proto3"

var (
	file_pkg_server_transport_grpc_proto_payload_proto_rawDescOnce sync.Once
	file_pkg_server_transport_grpc_proto_payload_proto_rawDescData []byte
)

func file_pkg_server_transport_grpc_proto_payload_proto_rawDescGZIP() []byte {
	file_pkg_server_transport_grpc_proto_payload_proto_rawDescOnce.Do(func() {
		file_pkg_server_transport_grpc_proto_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_server_transport_grpc_proto_payload_proto_rawDesc), len(file_pkg_server_transport_grpc_proto_payload_proto_rawDesc)))
	})
	return file_pkg_server_transport_grpc_proto_payload_proto_rawDescData
}

var file_pkg_server_transport_grpc_proto_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_server_transport_grpc_proto_payload_proto_goTypes = []any{
	(*PayloadRequest)(nil),  // 0: coretransport.PayloadRequest
	(*PayloadResponse)(nil), // 1: coretransport.PayloadResponse
}
var file_pkg_server_transport_grpc_proto_payload_proto_depIdxs = []int32{
	0, // 0: coretransport.CoreTransport.Call:input_type -> coretransport.PayloadRequest
	1, // 1: coretransport.CoreTransport.Call:output_type -> coretransport.PayloadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_server_transport_grpc_proto_payload_proto_init() }
func file_pkg_server_transport_grpc_proto_payload_proto_init() {
	if File_pkg_server_transport_grpc_proto_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_server_transport_grpc_proto_payload_proto_rawDesc), len(file_pkg_server_transport_grpc_proto_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_server_transport_grpc_proto_payload_proto_goTypes,
		DependencyIndexes: file_pkg_server_transport_grpc_proto_payload_proto_depIdxs,
		MessageInfos:      file_pkg_server_transport_grpc_proto_payload_proto_msgTypes,
	}.Build()
	File_pkg_server_transport_grpc_proto_payload_proto = out.File
	file_pkg_server_transport_grpc_proto_payload_proto_goTypes = nil
	file_pkg_server_transport_grpc_proto_payload_proto_depIdxs = nil
}
